### ISSUE TITLE
Incompatible with Unity 2022.3 LTS

### ISSUE THREAD

**Issue by tawi1** [tertle/com.unity.physics#3]
RigidbodyBakingSystem.cs:112 missing preprocessor directive for Unity 2022.3 LTS
RigidbodyBakingSystem.cs:113 missing preprocessor directive for Unity 2022.3 LTS
RigidbodyConversionTests.cs:114 missing preprocessor directive for Unity 2022.3 LTS
Can you make an update plz?

**Comment by tertle** [comment]
This should be fixed, I've wrapped them.
